######################
###  Input values  ###
######################

sample: 'data/sample.fastq'
ref_dir: 'data'
ref_name: 'ref.fa'
res_dir: 'results'

######################
### Default values ###
######################

seqkit_stats_options: '-a'
seqkit_seq_options: '-g'
fgbio_options: '--clip-overlapping-reads -c Hard -m' #
samtools_flagstat_options: ''
samtools_view_options: '-bhS -F 4'
samtools_sort_options: '-l 9'
samtools_index_options: ''
bamCoverage_options: '--normalizeUsing RPGC -of "bedgraph"'
plotCoverage_options: '--smartLabels --plotFileFormat pdf'
sniffles_options: '--minsvlen 10 --minsupport 10'
bcftools_stats_options: ''
combisv_options: ''
bcftools_filter_options: '-e "AF<0.1"'
bgzip_options: ''
tabix_options: ''
bcftools_merge_options: ''