######################
###  Input values  ###
######################

sample: 'data/sample.fastq'
ref: 'data/ref.fa'
res_dir: 'results'

######################
### Default values ###
######################

seqkit_stats_options: '-a'
seqkit_seq_options: '-g'
fastp_trim: '--trim_poly_x --overrepresentation_analysis'
fgbio_options: '--clip-overlapping-reads -c Hard -m'
samtools_index_options: ''
samtools_view_options: '-bhS -F 4'
samtools_sort_options: '-l 9'
bamCoverage_options: '--normalizeUsing RPGC -of "bedgraph"'
plotCoverage_options: '--smartLabels --plotFileFormat pdf'
gatk_calling_options: '--standard-min-confidence-threshold-for-calling 30.0 --dont-use-soft-clipped-bases true --sample-ploidy 2'
filter_snps_options: '--select-type-to-include SNP'
bcftools_filter_options: '-e "AF<0.1"'
cutesv_options: ''